### ISSUE TITLE
[Bug] Buttons and images are cropped if Windows 125%, 150% and Browser 75% and lower

### ISSUE THREAD

**Issue by InaLazarava** [epam/deps-fe-labeling-tool#15]
Buttons and images are cropped if Windows 125%, 150% and Browser 75% and lower:
 - Label, Table, Detect Table in dropdown list in the top panel
 - Table Data image in 'Properties' tab
 - Field's images in 'Assign to' tab

Browser: Google Chrome Version 116.0.5845.188 (Official Build) (64-bit)
Browser Zoom: 75% and lower
Windows Zoom: 125%, 150%

Precondition: document with all types of fields and labeled table exists in the system

Steps to reproduce:
1. Click on arrow near 'Label' button

ER: Dropdown list appears. All images are fully visible
AR: Dropdown list appears. All images are cropped 

2. Double click on labelled table

ER: On 'Properties' tab information about table appears. Table Data image is fully visible
AR: On 'Properties' tab information about table appears. Table Data image is cropped 

3. Click on 'Assign to' tab

ER: All field's images are fully visible
AR: All field's images are cropped

**Comment by DrDiman** [comment]
![image](https://github.com/epam/deps-fe-labeling-tool/assets/35468938/8ab0aa58-fe01-4804-ae91-e9a73576d15b)
![image](https://github.com/epam/deps-fe-labeling-tool/assets/35468938/e0c0d209-5794-4b91-be19-545eeb2f5ea0)
![image](https://github.com/epam/deps-fe-labeling-tool/assets/35468938/0d022964-5d9f-4311-a8b3-52d3a5d2c6ac)
